# install libraries needed for all codes (if not already installed) 

if (!require('caTools')) install.packages('caTools')
if (!require('cowplot')) install.packages('cowplot')
if (!require('curl')) install.packages('curl')
if (!require('data.table')) install.packages('data.table')
if (!require('edarf')) devtools::install_github('zmjones/edarf', subdir = 'pkg')
if (!require('ggplot2')) install.packages('ggplot2')
if (!require('httr')) install.packages('httr')
if (!require('ncdf4')) install.packages('ncdf4')
if (!require('quantregForest')) install.packages('quantregForest')
if (!require('smotefamily')) install.packages('smotefamily')
if (!require('patchwork')) install.packages('patchwork')
if (!require('tidyverse')) install.packages('tidyverse')
if (!require('wesanderson')) install.packages('wesanderson')
